# Generated by Django 2.0.2 on 2018-03-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='level',
        ),
    ]
