# Generated by Django 2.0.2 on 2018-03-02 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Position'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Section'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='superior',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
