# Generated by Django 2.0.2 on 2018-03-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180302_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('mule', '男'), ('fe_mule', '女'), ('un_know', '保密')], default='un_know', max_length=7),
        ),
    ]
