# Generated by Django 2.0.2 on 2018-03-03 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180303_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Position'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Section'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='superior',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
