# Generated by Django 2.0.2 on 2018-03-10 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20180310_2108'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.IntegerField(verbose_name='得分')),
                ('text', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('is_active', models.BooleanField(default=True)),
                ('total_score', models.IntegerField(verbose_name='总得分')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_level_answerSheet', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_level_answerSheet', to=settings.AUTH_USER_MODEL, verbose_name='受评人')),
            ],
            options={
                'verbose_name': '答卷',
                'verbose_name_plural': '答卷',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=20, verbose_name='评价指标')),
                ('question_content', models.CharField(max_length=200, verbose_name='评价要素')),
                ('full_score', models.IntegerField(verbose_name='标准分值')),
                ('required', models.BooleanField(default=True, help_text='这个问题是否必须回答')),
                ('order_in_list', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('down2up', '下对上'), ('up2down', '上对下'), ('up2up', '平级')], default='up2up', max_length=20, verbose_name='类型')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='score.Questionnaire'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='questionnaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_level_answerSheet', to='score.Questionnaire', verbose_name='对应问卷'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerSheet_level_answer', to='score.AnswerSheet'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_level_answer', to='score.Question'),
        ),
    ]
