# Generated by Django 2.0.2 on 2018-03-11 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerSheet_level_answer', to='score.AnswerSheet', verbose_name='对应答卷'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choices',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_level_answer', to='score.Question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='total_score',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='总得分'),
        ),
    ]
