# Generated by Django 2.0.2 on 2018-03-02 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('judges', models.ManyToManyField(related_name='judges_level_questionnaire', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
                ('players', models.ManyToManyField(related_name='players_level_questionnaire', to=settings.AUTH_USER_MODEL, verbose_name='受评人')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
                'ordering': ['-created_at'],
            },
        ),
    ]
