# Generated by Django 2.0.2 on 2018-03-02 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.IntegerField(verbose_name='得分')),
                ('text', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('is_active', models.BooleanField(default=True)),
                ('total_score', models.IntegerField(verbose_name='总得分')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_level_answerSheet', to=settings.AUTH_USER_MODEL, verbose_name='评分人')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_level_answerSheet', to=settings.AUTH_USER_MODEL, verbose_name='受评人')),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_level_answerSheet', to='scores.Questionnaire', verbose_name='对应问卷')),
            ],
            options={
                'verbose_name': '答卷',
                'verbose_name_plural': '答卷',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=20, verbose_name='评价指标')),
                ('question_content', models.CharField(max_length=200, verbose_name='评价要素')),
                ('full_score', models.IntegerField(verbose_name='标准分值')),
                ('required', models.BooleanField(default=True, help_text='这个问题是否必须回答')),
                ('order_in_list', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scores.Questionnaire')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerSheet_level_answer', to='scores.AnswerSheet'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_level_answer', to='scores.Question'),
        ),
    ]
